# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Node.js LTS Alpine base image
FROM node:lts-alpine

# Create and set working directory
WORKDIR /app

# Copy package.json and tsconfig
COPY package.json tsconfig.json ./

# Copy source code
COPY src ./src

# Install dependencies and build
RUN npm install && npm run build && npm prune --production

# Set production environment
ENV NODE_ENV=production

# Expose no external port; uses stdio

# Default command to start MCP server
ENTRYPOINT ["node", "build/index.js"]
